package data.purchasedata;

import java.util.ArrayList;
import dataenum.ResultMessage;
import org.junit.*;
import po.PurchasePO;
import dataenum.findtype.FindSalesType;
import dataenum.Warehouse;
import dataenum.BillType;
import po.commodity.CommodityItemPO;
import dataenum.BillState;
import static org.junit.Assert.*;

/**
 * The class <code>PurchaseDataTest</code> contains tests for the class <code>{@link PurchaseData}</code>.
 *
 * @generatedBy CodePro at 18-1-12 下午9:26
 * @author asus
 * @version $Revision: 1.0 $
 */
public class PurchaseDataTest {
	/**
	 * Run the PurchaseData() constructor test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testPurchaseData_1()
		throws Exception {

		PurchaseData result = new PurchaseData();

		// add additional test code here
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_1()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.delete(PurchaseData.java:86)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_2()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.delete(PurchaseData.java:86)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_3()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.delete(PurchaseData.java:86)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_4()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.delete(PurchaseData.java:86)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_5()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.delete(PurchaseData.java:86)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_1()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_2()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_3()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_4()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_5()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_6()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_7()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_8()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_9()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_10()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_11()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_12()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_13()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_14()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_15()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_16()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<PurchasePO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.find(PurchaseData.java:116)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_1()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_2()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_3()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_4()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_5()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_6()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_7()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_8()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_9()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_10()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_11()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_12()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_13()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_14()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_15()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.insert(PurchaseData.java:53)
		assertNotNull(result);
	}

	/**
	 * Run the void main(String[]) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testMain_1()
		throws Exception {
		String[] args = new String[] {};

		PurchaseData.main(args);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		//       at data.purchasedata.PurchaseData.main(PurchaseData.java:45)
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_1()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_2()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_3()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_4()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_5()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_6()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_7()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_8()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_9()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_10()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_11()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_12()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_13()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<PurchasePO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_14()
		throws Exception {
		PurchaseData fixture = new PurchaseData();

		ArrayList<PurchasePO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.show(PurchaseData.java:168)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_1()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.update(PurchaseData.java:100)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_2()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.update(PurchaseData.java:100)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_3()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.update(PurchaseData.java:100)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_4()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.update(PurchaseData.java:100)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_5()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.update(PurchaseData.java:100)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(PurchasePO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_6()
		throws Exception {
		PurchaseData fixture = new PurchaseData();
		PurchasePO po = new PurchasePO("", "", "", Warehouse.WAREHOUSE1, "", new ArrayList(), "", 1.0, BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.purchasedata.PurchaseData.update(PurchaseData.java:100)
		assertNotNull(result);
	}

	/**
	 * Perform pre-test initialization.
	 *
	 * @throws Exception
	 *         if the initialization fails for some reason
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Before
	public void setUp()
		throws Exception {
		// add additional set up code here
	}

	/**
	 * Perform post-test clean-up.
	 *
	 * @throws Exception
	 *         if the clean-up fails for some reason
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@After
	public void tearDown()
		throws Exception {
		// Add additional tear down code here
	}

	/**
	 * Launch the test.
	 *
	 * @param args the command line arguments
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	public static void main(String[] args) {
		new org.junit.runner.JUnitCore().run(PurchaseDataTest.class);
	}
}