package data.salesdata;

import java.util.ArrayList;
import dataenum.ResultMessage;
import org.junit.*;

import po.commoditypo.CommodityItemPO;
import po.commoditypo.GiftPO;
import po.salespo.SalesPO;
import dataenum.Warehouse;
import dataenum.findtype.FindSalesType;
import dataenum.BillType;
import dataenum.BillState;
import static org.junit.Assert.*;

/**
 * The class <code>SalesDataTest</code> contains tests for the class
 * <code>{@link SalesData}</code>.
 *
 * @generatedBy CodePro at 18-1-12 下午9:28
 * @author asus
 * @version $Revision: 1.0 $
 */
public class SalesDataTest {
	/**
	 * Run the SalesData() constructor test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testSalesData_1() throws Exception {

		SalesData result = new SalesData();

		// add additional test code here
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testDelete_1() throws Exception {
		SalesData fixture = new SalesData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.delete(SalesData.java:95)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testDelete_2() throws Exception {
		SalesData fixture = new SalesData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.delete(SalesData.java:95)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testDelete_3() throws Exception {
		SalesData fixture = new SalesData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.delete(SalesData.java:95)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testDelete_4() throws Exception {
		SalesData fixture = new SalesData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.delete(SalesData.java:95)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_1() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_2() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_3() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_4() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_5() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_6() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_7() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_8() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_9() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_10() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_11() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_12() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_13() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_14() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_15() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> find(String,FindSalesType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testFind_16() throws Exception {
		SalesData fixture = new SalesData();
		String keyword = "";
		FindSalesType type = FindSalesType.ID;

		ArrayList<SalesPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.find(SalesData.java:123)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_1() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_2() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_3() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_4() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO();

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_5() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_6() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_7() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_8() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_9() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_10() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_11() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_12() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_13() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_14() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testInsert_15() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.insert(SalesData.java:62)
		assertNotNull(result);
	}

	/**
	 * Run the void main(String[]) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testMain_1() throws Exception {
		String[] args = new String[] {};

		SalesData.main(args);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		// at data.salesdata.SalesData.main(SalesData.java:51)
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_1() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_2() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_3() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_4() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_5() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_6() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_7() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_8() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_9() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_10() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_11() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_12() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_13() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<SalesPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testShow_14() throws Exception {
		SalesData fixture = new SalesData();

		ArrayList<SalesPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.show(SalesData.java:173)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testUpdate_1() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.update(SalesData.java:108)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testUpdate_2() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO();

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.update(SalesData.java:108)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testUpdate_3() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO();

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.update(SalesData.java:108)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testUpdate_4() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.update(SalesData.java:108)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(SalesPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Test
	public void testUpdate_5() throws Exception {
		SalesData fixture = new SalesData();
		SalesPO po = new SalesPO("", "", "", "", "", Warehouse.WAREHOUSE1, new ArrayList(), new ArrayList(), 1.0, 1.0,
				1.0, 1.0, "", BillType.INVENTORYGIFTBILL, BillState.COMMITED);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this
		// test:
		// java.lang.NullPointerException
		// at data.salesdata.SalesData.update(SalesData.java:108)
		assertNotNull(result);
	}

	/**
	 * Perform pre-test initialization.
	 *
	 * @throws Exception
	 *             if the initialization fails for some reason
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@Before
	public void setUp() throws Exception {
		// add additional set up code here
	}

	/**
	 * Perform post-test clean-up.
	 *
	 * @throws Exception
	 *             if the clean-up fails for some reason
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	@After
	public void tearDown() throws Exception {
		// Add additional tear down code here
	}

	/**
	 * Launch the test.
	 *
	 * @param args
	 *            the command line arguments
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:28
	 */
	public static void main(String[] args) {
		new org.junit.runner.JUnitCore().run(SalesDataTest.class);
	}
}