package data.classificationdata;

import java.util.ArrayList;
import org.junit.*;
import po.ClassificationVPO;
import dataenum.ResultMessage;
import static org.junit.Assert.*;

/**
 * The class <code>ClassificationDataTest</code> contains tests for the class <code>{@link ClassificationData}</code>.
 *
 * @generatedBy CodePro at 18-1-12 下午9:26
 * @author asus
 * @version $Revision: 1.0 $
 */
public class ClassificationDataTest {
	/**
	 * Run the ClassificationData() constructor test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testClassificationData_1()
		throws Exception {

		ClassificationData result = new ClassificationData();

		// add additional test code here
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_1()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "灯";

		ResultMessage result = fixture.delete(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.delete(ClassificationData.java:103)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_2()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "灯";

		ResultMessage result = fixture.delete(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.delete(ClassificationData.java:103)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_3()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "灯";

		ResultMessage result = fixture.delete(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.delete(ClassificationData.java:103)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_4()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "灯";

		ResultMessage result = fixture.delete(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.delete(ClassificationData.java:103)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_5()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "灯";

		ResultMessage result = fixture.delete(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.delete(ClassificationData.java:103)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_1()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_2()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_3()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_4()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_5()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_6()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_7()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_8()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_9()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_10()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_11()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_12()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_13()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> find(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_14()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String keyword = "";

		ArrayList<ClassificationVPO> result = fixture.find(keyword);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.find(ClassificationData.java:133)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_1()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_2()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_3()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_4()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "灯";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_5()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_6()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_7()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_8()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_9()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_10()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_11()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_12()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO findClassification(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFindClassification_13()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		String name = "";

		ClassificationVPO result = fixture.findClassification(name);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.findClassification(ClassificationData.java:207)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO getRoot() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testGetRoot_1()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ClassificationVPO result = fixture.getRoot();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		//       at data.classificationdata.ClassificationData.getRoot(ClassificationData.java:193)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO getRoot() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testGetRoot_2()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ClassificationVPO result = fixture.getRoot();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		//       at data.classificationdata.ClassificationData.getRoot(ClassificationData.java:193)
		assertNotNull(result);
	}

	/**
	 * Run the ClassificationVPO getRoot() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testGetRoot_3()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ClassificationVPO result = fixture.getRoot();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		//       at data.classificationdata.ClassificationData.getRoot(ClassificationData.java:193)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_1()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.insert(ClassificationData.java:78)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_2()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.insert(ClassificationData.java:78)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_3()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.insert(ClassificationData.java:78)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_4()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.insert(ClassificationData.java:78)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_5()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.insert(ClassificationData.java:78)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_6()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.insert(ClassificationData.java:78)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_7()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.insert(ClassificationData.java:78)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_8()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.insert(ClassificationData.java:78)
		assertNotNull(result);
	}

	/**
	 * Run the void main(String[]) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testMain_1()
		throws Exception {
		String[] args = new String[] {};

		ClassificationData.main(args);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		//       at data.classificationdata.ClassificationData.main(ClassificationData.java:50)
	}

	/**
	 * Run the void main(String[]) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testMain_2()
		throws Exception {
		String[] args = new String[] {};

		ClassificationData.main(args);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		//       at data.classificationdata.ClassificationData.main(ClassificationData.java:50)
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_1()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_2()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_3()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_4()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_5()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_6()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_7()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_8()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_9()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_10()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_11()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_12()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_13()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<ClassificationVPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_14()
		throws Exception {
		ClassificationData fixture = new ClassificationData();

		ArrayList<ClassificationVPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.show(ClassificationData.java:167)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_1()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.update(ClassificationData.java:117)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_2()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.update(ClassificationData.java:117)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_3()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.update(ClassificationData.java:117)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_4()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.update(ClassificationData.java:117)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_5()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.update(ClassificationData.java:117)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(ClassificationVPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_6()
		throws Exception {
		ClassificationData fixture = new ClassificationData();
		ClassificationVPO po = new ClassificationVPO("", "", new Boolean(true), "", new ArrayList(), new ArrayList());

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.classificationdata.ClassificationData.update(ClassificationData.java:117)
		assertNotNull(result);
	}

	/**
	 * Perform pre-test initialization.
	 *
	 * @throws Exception
	 *         if the initialization fails for some reason
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Before
	public void setUp()
		throws Exception {
		// add additional set up code here
	}

	/**
	 * Perform post-test clean-up.
	 *
	 * @throws Exception
	 *         if the clean-up fails for some reason
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@After
	public void tearDown()
		throws Exception {
		// Add additional tear down code here
	}

	/**
	 * Launch the test.
	 *
	 * @param args the command line arguments
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	public static void main(String[] args) {
		new org.junit.runner.JUnitCore().run(ClassificationDataTest.class);
	}
}