package data.accountdata;

import java.util.ArrayList;
import org.junit.*;
import po.AccountPO;
import dataenum.findtype.FindAccountType;
import dataenum.ResultMessage;
import static org.junit.Assert.*;

/**
 * The class <code>AccountDataTest</code> contains tests for the class <code>{@link AccountData}</code>.
 *
 * @generatedBy CodePro at 18-1-12 下午9:26
 * @author asus
 * @version $Revision: 1.0 $
 */
public class AccountDataTest {
	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_1()
		throws Exception {
		AccountData fixture = new AccountData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.delete(AccountData.java:75)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_2()
		throws Exception {
		AccountData fixture = new AccountData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.delete(AccountData.java:75)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_3()
		throws Exception {
		AccountData fixture = new AccountData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.delete(AccountData.java:75)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_4()
		throws Exception {
		AccountData fixture = new AccountData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.delete(AccountData.java:75)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_5()
		throws Exception {
		AccountData fixture = new AccountData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.delete(AccountData.java:75)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage delete(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testDelete_6()
		throws Exception {
		AccountData fixture = new AccountData();
		String id = "";

		ResultMessage result = fixture.delete(id);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.delete(AccountData.java:75)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_1()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_2()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_3()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_4()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_5()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_6()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_7()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_8()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_9()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_10()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_11()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_12()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_13()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_14()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_15()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> find(String,FindAccountType) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testFind_16()
		throws Exception {
		AccountData fixture = new AccountData();
		String keyword = "";
		FindAccountType type = FindAccountType.ID;

		ArrayList<AccountPO> result = fixture.find(keyword, type);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.find(AccountData.java:140)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_1()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_2()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_3()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_4()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_5()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_6()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_7()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_8()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_9()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_10()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_11()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_12()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_13()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_14()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage insert(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testInsert_15()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.insert(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.insert(AccountData.java:44)
		assertNotNull(result);
	}

	/**
	 * Run the void main(String[]) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testMain_1()
		throws Exception {
		String[] args = new String[] {};

		AccountData.main(args);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		//       at data.accountdata.AccountData.main(AccountData.java:34)
	}

	/**
	 * Run the void main(String[]) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testMain_2()
		throws Exception {
		String[] args = new String[] {};

		AccountData.main(args);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		//       at data.accountdata.AccountData.main(AccountData.java:34)
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_1()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_2()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_3()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_4()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_5()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_6()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_7()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_8()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_9()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_10()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_11()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_12()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_13()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_14()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ArrayList<AccountPO> show() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testShow_15()
		throws Exception {
		AccountData fixture = new AccountData();

		ArrayList<AccountPO> result = fixture.show();

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.show(AccountData.java:109)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_1()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.update(AccountData.java:91)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_2()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.update(AccountData.java:91)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_3()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.update(AccountData.java:91)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_4()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.update(AccountData.java:91)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_5()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.update(AccountData.java:91)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_6()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.update(AccountData.java:91)
		assertNotNull(result);
	}

	/**
	 * Run the ResultMessage update(AccountPO) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Test
	public void testUpdate_7()
		throws Exception {
		AccountData fixture = new AccountData();
		AccountPO po = new AccountPO("", "", 1.0);

		ResultMessage result = fixture.update(po);

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at data.accountdata.AccountData.update(AccountData.java:91)
		assertNotNull(result);
	}

	/**
	 * Perform pre-test initialization.
	 *
	 * @throws Exception
	 *         if the initialization fails for some reason
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@Before
	public void setUp()
		throws Exception {
		// add additional set up code here
	}

	/**
	 * Perform post-test clean-up.
	 *
	 * @throws Exception
	 *         if the clean-up fails for some reason
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	@After
	public void tearDown()
		throws Exception {
		// Add additional tear down code here
	}

	/**
	 * Launch the test.
	 *
	 * @param args the command line arguments
	 *
	 * @generatedBy CodePro at 18-1-12 下午9:26
	 */
	public static void main(String[] args) {
		new org.junit.runner.JUnitCore().run(AccountDataTest.class);
	}
}